name: iOS Build (Xcode)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

    #   - name: Generate missing platform folders
    #     run: flutter create .

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>destination</key>
              <string>export</string>
            </dict>
          </plist>
          EOF

      - name: Build with Xcode
        run: |
          cd ios
          # Clean previous builds
          xcodebuild clean \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release

          # Build archive without signing
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

          # Export unsigned IPA
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/ios

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/ios/*.ipa
